---
- name: Vérifier si le fichier teleport.yml existe déjà # mettre un nom explicite et pas une phrase
  ansible.builtin.shell: cat /etc/teleport.yaml
  register: file_exist
  failed_when: false
  changed_when: false
  tags: configuration

- name: Configuration du fichier teleport.yml # mettre un nom explicite et pas une phrase
  ansible.builtin.shell: |
    teleport configure -o file \
      --cluster-name=bastion.tom.lan \
      --public-addr=bastion.tom.lan:443 \
      --cert-file=/var/lib/teleport/fullchain.pem \
      --key-file=/var/lib/teleport/privkey.pem
  when: file_exist.rc != 0
  tags: configuration