---
- name: Vérification de la présence de l'utilisateur
  ansible.builtin.shell: tsh login --proxy=bastion.tom.lan --user=admin && tctl status
  register: exist
  failed_when: false
  changed_when: false
  tags: create_users

- name: Créer l'utilisateur
  ansible.builtin.shell: tctl users add admin --logins=admin,root --roles=access,editor
  when: exist.rc != 0
  tags: create_users
