---
- name: Vérifier si Teleport tourne
  ansible.builtin.command: systemctl is-active teleport
  register: teleport_running
  failed_when: false
  changed_when: false
  tags: start

- name: Activer Teleport automatiquement au boot 
  ansible.builtin.shell: systemctl enable --now teleport
  when: teleport_running.rc != 0
  tags: start