[infra]
bastion ansible_host=bastion.tom.lan

[monitoring]
grafana ansible_host=grafana.tom.lan
loki ansible_host=loki.tom.lan
prometheus ansible_host=prometheus.tom.lan

[database]
db ansible_host=db.tom.lan
backup ansible_host=backup.tom.lan

[dmz]
web ansible_host=web.tom.lan
proxy ansible_host=proxy.tom.lan

[dev]
dev-web ansible_host=dev-web.tom.lan
dev-db ansible_host=dev-db.tom.lan
runner ansible_host=runner.tom.lan

[all:vars]
ansible_user=admin
ansible_ssh_private_key_file=~/.ssh/id_ed25519
