#cloud-config

# ---------------------------------------------------------------------------
# 1. Identité (Indispensable pour éviter les conflits réseau entre les clones)
# ---------------------------------------------------------------------------
hostname: ${hostname}
fqdn: ${hostname}.${domain}
manage_etc_hosts: true

# ---------------------------------------------------------------------------
# 2. Accès et Sécurité (Pour injecter les clés SSH de l'utilisateur final)
# ---------------------------------------------------------------------------
users:
  - name: sysadmin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}

ssh_pwauth: false
disable_root: true

# ---------------------------------------------------------------------------
# 3. Gestion du disque (TRÈS IMPORTANT !)
# ---------------------------------------------------------------------------
# Si Terraform demande un disque plus grand que la template Packer d'origine,
# ceci force la partition racine à s'étendre pour utiliser tout le nouvel espace.
growpart:
  mode: auto
  devices: ["/"]

# ---------------------------------------------------------------------------
# 4. (Optionnel) Scripts spécifiques à cette instance
# ---------------------------------------------------------------------------
# runcmd:
#  - echo "Cette machine ${hostname} vient de naître d'une template Packer !" > /tmp/info.txt
