all:
  children:
    monitoring:
      vars:
        ansible_user: admin
      hosts:
        loki:
          ansible_host: 192.168.10.7
        grafana:
          ansible_host: 192.168.10.68
        prometheus:
          ansible_host: 192.168.10.52
    dmz:
      vars:
        ansible_user: admin
      hosts:
        bastion:
          ansible_host: 192.168.10.9
        reverse-proxy:
          ansible_host: 192.168.10.48
        ci-cd:
          ansible_host: 192.168.10.10
    develop:
      vars:
        ansible_user: admin
      hosts:
        dev:
          ansible_host: 192.168.10.67
        database:
          ansible_host: 192.168.10.24
