---
- name: init_teleport_enroll
  hosts: bastion
  become: true

  roles:
    - role: teleport/enroll_node

- name: add_resources
  hosts:
    - database
    - dev
    - monitoring
    - dmz
  become: true

  roles:
    - role: teleport/enroll_resources
