---
- name: verif_certificate_exist
  ansible.builtin.command: openssl x509 -noout -in /var/lib/teleport/fullchain.pem
  register: certificate_exist
  failed_when: false
  changed_when: false
  check_mode: false 

- name: get_certificate
  ansible.builtin.slurp:
    src: /var/lib/teleport/fullchain.pem
  register: certificate_file
  when: certificate_exist.rc == 0

- name: certificate_var
  set_fact:
    certificate: "{{certificate_file['content'] | b64decode }}"
  when: certificate_exist.rc == 0
